/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Faucet } from "./Faucet";
export type { Ownable } from "./Ownable";
export * as factories from "./factories";
export { Faucet__factory } from "./factories/Faucet__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
